- test_framework/test_jit.py
- tests/call-memfrob.data
- tests/call-save.data
- tests/call.data
- tests/err-call-bad-imm.data
- tests/err-call-unreg.data
- tests/err-div-by-zero-imm.data
- tests/err-endian-size.data
- tests/err-incomplete-lddw.data
- tests/err-incomplete-lddw2.data
- tests/err-infinite-loop.data
- tests/err-invalid-reg-dst.data
- tests/err-invalid-reg-src.data
- tests/err-jmp-lddw.data
- tests/err-jmp-out.data
- tests/err-noexit.data
- tests/err-too-many-instructions.data
- tests/err-unknown-opcode.data
- tests/err-write-r10.dst
- vm/inc/ubpf.h
- vm/test.c
- vm/ubpf_int.h
- vm/ubpf_jit.dasm
- vm/ubpf_vm.c
The application can register functions for the eBPF program to call. These are
named by the small integer index that goes in the call immediate.
In the near future I'll add an ELF loader that "relocates" call instructions,
inserting the called function's index into the bytecode after looking it up by
name.
> implement call instruction

- .travis.yml
- README.md
- requirements.txt
- test_framework/test_elf.py
- tests/elf/bad-section-header-offset.data
- tests/elf/bad-section-header-size.data
- tests/elf/bad-section-offset.data
- tests/elf/bad-section-size.data
- tests/elf/ehdr-short.data
- tests/elf/no-text-section.data
- tests/elf/ok.data
- tests/elf/rel-section.data
- tests/elf/wrong-byte-order.data
- tests/elf/wrong-class.data
- tests/elf/wrong-machine.data
- tests/elf/wrong-osabi.data
- tests/elf/wrong-type.data
- tests/elf/wrong-version.data
- vm/Makefile
- vm/inc/ubpf.h
- vm/test.c
- vm/ubpf_loader.c
This simplifies running programs compiled by Clang because the user doesn't
need to extract the eBPF instructions from the object file. In the future
we'll use ELF to carry more information, such as function call relocations
and maps.
> basic ELF loader

- vm/ubpf_jit_x86_64.c
As described in #9 there is a problem with the saving the reference to the stack after the allocation.
The stack allocation (see below) will allocate the stack space but also modify the stack pointer to the top of the newly allocated stack space.
```
/* Allocate stack space */
emit_alu64_imm32(state, 0x81, 5, RSP, STACK_SIZE);
```
Therefore the code must be changed to first save the stack pointer to R10 and then be allocated in order to have R10 to point to the bottom of the stack.
> Save the stack pointer before allocating new stack space, fix #9

- vm/test.c
This PR contains some small fixes for options handling in the `test` executable, under `vm/` directory, about the following points:
* `-e`/`--elf` options are unused.
* `struct option` for `getopt_long()` does not end with an empty element, making the executable crash on unknown long options.
* `--jit` should point on `-j` instead of `-m`.
> Small fixes for options handling in vm/test.c

- test_framework/test_elf.py
With the last pyelftools version, ELFStructs' attributes now need to be explicitly initialized.
This pull request thereby fixes the Travis CI builds.
> Fix tests for new pyelftools version

- README.md
- vm/Makefile
In order to use the ubpf static library in other applications it is
useful to have a "make install" target. We place the relevent files
(libubpf.a and ubpf.h) into the /usr/local tree at the right spots to
allow other programs to reference them.
Signed-off-by: Stephen Bates <sbates@raithlin.com>
> vm/Makefile: Add an install target

- .gitignore
This pull request adds a `.gitignore` file to stop all of the `.pyc` files from showing up in git. This `.gitignore` file for Python was taken from https://github.com/github/gitignore.
> Add default Python gitignore configuration

- tests/err-noexit.data
- tests/exit-not-last.data
- vm/ubpf_vm.c
Negative jump offsets are valid in eBPF. Thus, while all paths through the CFG should end with an exit instruction, it is not necessarily the last instruction.
> Negative jump offsets are valid in eBPF

- .travis.yml
- bin/ubpf-assembler
- bin/ubpf-disassembler
- requirements.txt
- test_framework/test_assembler.py
- test_framework/test_disassembler.py
- test_framework/test_elf.py
- test_framework/test_jit.py
- test_framework/test_vm.py
- test_framework/testdata.py
- tests/elf/ehdr-short.data
- ubpf/asm_parser.py
- ubpf/assembler.py
- ubpf/disassembler.py
This PR adds python3 support to `ubpf-(dis)assembler.py`. nosetest gives the same result with both python2 (2.7.13) and python3 (3.6.9) on my environment (Ran 858 tests, OK (SKIP=475)).
Signed-off-by: Masanori Misono <m.misono760@gmail.com>
> Python3 support

- vm/inc/ubpf.h
- vm/ubpf_int.h
- vm/ubpf_vm.c
bounds_check routine assumes that memory to read / write may only be on the stack or within ubpf code itself.
The toggle allows disabling the check when the assumption is not correct.
> Introduce toggle to enable/disable bounds_check.

- vm/inc/ubpf.h
Commit 089f627 added the bool type to an external function but did not
add the approriate header to define that type. This still allowed the
library to be built because <stdbool.h> was included in the internal
library source files. However it causes issues when linking to this
library from other programs.
Fixes #38
> ubpf.h: Add <stdbool.h> to external header file

- test_framework/testdata.py
I ran into errors like `RuntimeError: dictionary keys changed during iteration` during testing; this fixes those for me.
> testdata: Don't modify keys while iterating

- .travis.yml
Newer versions of pip are required to install recent versions of `cpp-coveralls`. However, pip >= 21 is incompatible with Python 3.5.
> .travis: Fix Python3.5 build

- vm/inc/ubpf.h
- vm/ubpf_int.h
- vm/ubpf_jit_x86_64.c
- vm/ubpf_vm.c
Minimal set of changes required to work with Windows eBPF project
Resolves: #61
> Minimal set of changes required to work with Windows eBPF project

- vm/inc/ubpf.h
- vm/ubpf_int.h
- vm/ubpf_jit_x86_64.c
- vm/ubpf_vm.c
Permit overriding maximum stack size at compile time.
Resolves: #65 
> Permit overriding maximum stack size

- tests/mem-len.data
- vm/ubpf_vm.c
It is useful for programs to be able to operate based on the length of
the input data passed in to it. Pass in this length via the R2
register.
Fixes #57.
> ubpf_vm: Add mem_len via R2 into uBPF VM

- vm/ubpf_jit_x86_64.c
Fix register mapping to avoid volatile registers and issues with R12
Resolves: #77 
> Fix register mapping to avoid volatile registers and issues with R12

- vm/inc/ubpf.h
- vm/test.c
- vm/ubpf_vm.c
ubpf_exec should separate errors returned from the return value
Resolves: #79 
> ubpf_exec should separate errors returned from the return value

- tests/call_unwind.data
- tests/call_unwind_fail.data
- vm/inc/ubpf.h
- vm/test.c
- vm/ubpf_int.h
- vm/ubpf_jit_x86_64.c
- vm/ubpf_jit_x86_64.h
- vm/ubpf_vm.c
bpf_tail_call has special semantics.
If the call returns success, then ubpf needs to store the return value and unwind the stack so to the caller.
Signed-off-by: Alan Jowett <Alan.Jowett@microsoft.com>
> Implement unwind on success semantics to support bpf_tail_call

- vm/ubpf_int.h
- vm/ubpf_jit_x86_64.c
- vm/ubpf_jit_x86_64.h
- vm/ubpf_vm.c
Make divide by zero handler address independent. 
1) Embed the format string into the machine code.
2) Use lea with RIP relative addressing to load address of format string.
> Make divide by zero handler address independent

- vm/Makefile
This is important for integration with languages like Julia which can only really access shared libraries.
> Build libubpf.so

- test_framework/test_elf.py
- test_framework/test_jit.py
- vm/Makefile
- vm/test.c
- vm/ubpf_int.h
- vm/ubpf_jit.c
- vm/ubpf_jit_x86_64.c
- vm/ubpf_vm.c
As a first step in adding an Arm64 JIT to ubpf this PR enables building the library on platforms with no JIT target implemented.  It also updates the testsuite to skip trying to run the JIT tests on those platforms.  It does this by adding a 'null' JIT that always fails.
The approach taken for the build system is to assume that all JITs (currently just x86_64 and null) will successfully build on all platforms, but that only the JIT required for the target platform will be used.
Building and testing on Arm64 platforms highlighted an issue with elftools which is worked around in the second commit.
This has been tested successfully on x86_64 and Arm64 platforms.
> Enable ubpf on platforms with no supported JIT

- vm/test.c
Building and running with Address Sanitizer enabled leads to failures on x86-64:
```
make -C vm ASAN=1
nosetests
```
These are all due to the test harness not freeing the memory allocated to hold the contents of the "-- mem" data.  Adding appropriate calls to `free()` fixes these issues.
Tested on x86-64.
> Fix Address Sanitizer failures

- vm/Makefile
- vm/inc/ubpf.h
- vm/ubpf_int.h
- vm/ubpf_vm.c
There are two different contributions in this PR. I can create two different PRs if needed.
The first one adds an install target to Makefile that places the static library + header in /usr/local.
The second exposes the VM registers to the user.
> Expose VM registers

- README.md
- test_framework/test_jit.py
- tests/stack3.data
- vm/Makefile
- vm/test.c
- vm/ubpf_int.h
- vm/ubpf_jit_arm64.c
- vm/ubpf_vm.c
This implements an Arm64 JIT for UBPF on Linux.
The JIT follows the same high-level structure as the x86-64 JIT.
Arm64 has a restricted number of immediates which can be used in instructions.  Therefore, when generating code UBPF instructions of the form `OP reg, imm` this is usually translated into `MOV temp_register, imm; OP reg, temp_register`.  Some instructions (ADD, SUB and compares) do have special cases for simple immediates.
Load stores similarly have a restricted range of immediates that can be used for load offsets.  This may mean that some loads/stores of the form `LD dest, [src+imm]` may be transformed into `MOV offset_register, imm; LDR dest, [src, offset_register]`
We also use an extra temporary register in code generation for MOD to store the result of the division before …
> Implement and enable Arm64 JIT

- vm/Makefile
When #97 and #48 were merged at the same time, certain symbols are included in `libubpf.a` but not in `libubpf.so`.
That causes linker errors such as:
```text
libndn-dpdk-c.a.p/csrc_strategycode_load.c.o: In function `StrategyCode_LoadUbpf':
build/../csrc/strategycode/load.c:40: undefined reference to `ubpf_compile'
```
This PR makes both static library and dynamic library include the same object files.
> vm: include ubpf_jit.o in dynamic library

- vm/CMakeLists.txt
Resolves: #110
Only add target_link_libraries for test code if UBPF_ENABLE_TESTS is set.
> Fix CMake to permit building without test libraries

- .travis.yml
This was tested using Travis CI.
arm64 has a few different steps to satisfy the dependencies on Xenial, but other than that, it should be straightforward.
> Add arm64 to Travis CI

- README.md
The README.md should document how to build uBPF using CMake and how to run the tests. 
Resolves: #120
> Document CMake building procedures

- vm/ubpf_loader.c
When loading ELF files we calculate the location of a section header in a way that can overflow a `uint32_t` value producing a wrong result.
This commit fixes the issue by using the fact that section headers are contiguous in the ELF file.
Resolves #147
> Fix potential integer overflow loading ELF files

- vm/Makefile
- vm/ubpf_jit_arm64.c
- vm/ubpf_loader.c
- vm/ubpf_vm.c
This PR fixes the UBSan failures found by testing #119.
The errors all fall into two categories:
* Undefined behaviour caused by integer promotions when generating Arm64 instruction patterns
* Undefined behaviour caused by data not being naturally aligned (includes portions of a patch already in #119).
Fixes #149.
Fixes #150.
Implementation note:
I did not change the instruction pattern generation to use packed structures, as I felt this would increase the amount of boiler plate code substantially (as instruction patterns are not consistent between different instruction classes).
> Fix all UBSan failures on Arm64

- vm/inc/ubpf.h
In my C++ use case for this library, I currently have 
```c++
extern "C" {
#include <ubpf.h>
}
```
to avoid my C++ compiler mangling the declarations, and then not finding the symbols. This is much like how `ubpf_plugin/ubpf_plugin.cc` does it.
Alternatively, this patch moves the `extern "C"` stuff into ubpf.h itself. As far as I can tell from building the project and running the tests, this has no effect (expectedly) for non-c++ users.
> Add support for C++ users

- vm/ubpf_vm.c
Fix sign mismatch that causes failure when building with /w4.
> Fix sign mismatch

- .github/workflows/posix.yml
> See if updating apt catalog fixes missing aarch64 bintools

- vm/ubpf_vm.c
Modify handling of EBPF_OP_LSH_IMM and EBPF_OP_LSH_REG to match Linux implementation.
Update bpf_conformance to latest.
> Fix handling of 32 bit left-shift operations in interperter

- .github/workflows/main.yml
- .github/workflows/posix.yml
- CMakeLists.txt
- aarch64_test/CMakeLists.txt
- aarch64_test/run-interpret.sh
- aarch64_test/run-jit.sh
- bpf/CMakeLists.txt
- cmake/options.cmake
- ubpf_plugin/CMakeLists.txt
Currently the CI/CD runs a set of tests based on [bpf_conformance](https://github.com/Alan-Jowett/bpf_conformance) but ctest doesn't run these.
Resolves: #266
> Add ctest based tests to run bpf_conformance tests.

- vm/ubpf_int.h
- vm/ubpf_jit_arm64.c
- vm/ubpf_jit_x86_64.c
- vm/ubpf_vm.c
Re-enabling required properly handling the home space on the stack when using the fastcall calling convention.
Note: There is an open issue about stack alignment requirements now falling on the shoulders of the ebpf compiler (or program writer).
> Re-enable support for local calls on Windows (x86_64)

- vm/ubpf_vm.c
The calloc API returns NULL on out of memory. To prevent dereferencing NULL, we need to check for that case.
Resolves: #298
> Add out of memory check

- vm/ubpf_vm.c
Replace return N; calls with jump to common exit point to permit cleanup of allocated stack space.
> Fix memory leak in ubpf_exec

- ubpf_plugin/CMakeLists.txt
Now that `bpf_conformance` has tests that are expected to fail, we should probably make it easier to add such tests.
> Expandable support for tests expected to fail

- vm/ubpf_jit_x86_64.c
We are going to stay entirely away from using R12. Make documentation updates to make that clear. At the same time, fix a bug where the jitter was not properly resilient to a list of non-volatile registers that was not divisible by 16.
> Note special status of R12 in x86_64 jitter

- .github/workflows/main.yml
- .github/workflows/posix.yml
- .github/workflows/windows.yml
- cmake/options.cmake
- cmake/settings.cmake
- vm/ubpf_jit_x86_64.c
- vm/ubpf_jit_x86_64.h
Spectre/Meltdown lurk where indirect calls are used. Let's protect against the badness if we can.
> Add retpoline mitigation for x86-64 Linux indirect calls

- vm/ubpf_jit_x86_64.c
- vm/ubpf_jit_x86_64.h
All division by zero is handled by the ISA and does not trigger an exception.
> Remove division-by-zero handling in x86 JIT

- cmake/options.cmake
- cmake/settings.cmake
- vm/ubpf_config.h.inc
Disable retpoline code on Windows until #320 is fixed.
> Disable retpoline on Windows by default until fixed

- cmake/options.cmake
- vm/ubpf_jit_x86_64.c
There is a call embedded in the retpoline that also needs home space. It is possible that the final call will need that home space, too. For now, we will go without.
> Create home space properly for Windows retpolines

- .github/workflows/posix.yml
- .github/workflows/windows.yml
Add check for return code from bpf_conformance runner and fail CI/CD pipeline if it returns != 0.
> Check for return code from tests

- .github/workflows/main.yml
CI/CD fails if other jobs complete first.
> Add dependency on macos_release/debug_coverage_no_retpolines

- .github/scripts/build-libbpf.sh
- .github/workflows/main.yml
- .github/workflows/posix.yml
The updated bpf_conformance requires a new(er) version of libbpf than is available on github runners. With this change, we build our own version of libbpf from source so that we are using a new(er) version of the library with all the necessary features.
> Fix CI/CD for updated bpf_conformance

- README.md
- scripts/build-libbpf.sh
Refactored and added steps in readme for build steps in linux system.
Copied libbpf build script to `scripts/`
> Added linux build steps 

- .gitmodules
- CMakeLists.txt
- ubpf_plugin/CMakeLists.txt
1. Make sure that tests that require external packages do not try to build when the user has opted out of external packages.
2. Integrate git submodules with external projects (CMake) for the best of both worlds!
> More External Project Configuration Updates

- tests/mul-loop-memory-iterations.data
- ubpf_plugin/ubpf_plugin.cc
When there is no user-specified starting contents for the memory when using ubpf_plugin, the vector representing the contents of the memory is empty. There was an assumption that when the size of a std::vector is 0 then std::vector::data will return a null pointer but this is not guaranteed to be the case.
Issue found while trying to debug tests/mul-loop.data failure in wasm platform.
> Fix ubpf_plugin passing ambiguous pointer to memory for ubpf_exec

- tests/div32-by-zero-reg.data
- vm/ubpf_vm.c
When checking whether the operand is not 0, one should only look on 32 bits when doing a 32 bits operation.
> Prevent division by 0

- vm/ubpf_vm.c
This pull request includes a crucial change to the `validate` function in the `vm/ubpf_vm.c` file. The condition checking the `call_target` variable has been updated to prevent out-of-bounds access. Previously, the condition allowed for `call_target` to be equal to `num_insts`, which could potentially lead to accessing an element beyond the array's limit. Now, the condition has been corrected to `call_target >= num_insts`, ensuring that `call_target` stays within the valid range of array indices.
> Reject BPF programs with jump targets outside of range of instructions.

- .github/workflows/fuzzing.yml
- .github/workflows/main.yml
- CMakeLists.txt
- cmake/options.cmake
- cmake/settings.cmake
- libfuzzer/CMakeLists.txt
- libfuzzer/libfuzz_harness.cc
- vm/inc/ubpf.h
- vm/ubpf_int.h
- vm/ubpf_vm.c
This pull request introduces fuzzing capabilities to the project, including a new GitHub Actions workflow, and modifies the project's build system to support fuzzing. The most significant changes include the addition of the `fuzzing.yml` workflow, the introduction of a new `ubpf_fuzzer` executable, and the modification of the `ubpf_vm` structure to include an instruction limit.
New GitHub Actions workflow:
* [`.github/workflows/fuzzing.yml`](diffhunk://#diff-0d1818478ed3978a08c330da0345293a51e13da847c4f41d494b346c3615b94cR1-R162): Added a new workflow to perform fuzzing. This workflow includes steps to build the project with fuzzing enabled, run the fuzzer, and upload any found artifacts.
Modifications to existing GitHub Actions workflow:
* …
> Add libfuzzer based test with 

- vm/ubpf_jit_x86_64.c
This pull request contains a modification to the `muldivmod` function in the `vm/ubpf_jit_x86_64.c` file. The change is in the condition for loading the divisor into the RCX register. Previously, the divisor was loaded if `imm` was true. The updated code now loads the divisor if `reg` is not true. This change might affect how the divisor is loaded into the RCX register depending on the value of `reg`.
> Use flag instead of imm value to determine if this is register to register operation

- ubpf/disassembler.py
This pull request primarily focuses on enhancing the `ubpf/disassembler.py` script with support for 32-bit jumps in the eBPF bytecode disassembly process. The changes include the addition of a new opcode and class for 32-bit jumps, and an update to the `disassemble_one` function to handle the new opcode and class.
Here are the key changes:
* [`ubpf/disassembler.py`](diffhunk://#diff-d90f98ac0def87d3c80ca75f0f13e5831bb21e5b0ab9752962d062e97f79057bR16): Added a new opcode `jmp32` to the `JMP_OPCODES` dictionary, which maps opcodes to their string names.
* [`ubpf/disassembler.py`](diffhunk://#diff-d90f98ac0def87d3c80ca75f0f13e5831bb21e5b0ab9752962d062e97f79057bR75): Introduced a new class `BPF_CLASS_JMP32` with a value of 6, representing the class for 32-bit jumps.
* …
> Add JMP32 class to disassembler

- vm/ubpf_vm.c
Resolves: #444 
Interpreter wasn't correctly sign extending the immediate value before comparing it to the register.
> Fix behavior around jumps with immediate values > 0x7fffffff in the interpreter

- .github/workflows/fuzzing.yml
- .github/workflows/main.yml
This pull request includes changes to the GitHub Actions workflow files `.github/workflows/fuzzing.yml` and `.github/workflows/main.yml`. The changes mainly involve the modification of the fuzzing workflow, including the change of permissions, scheduling, and the use of environment variables instead of inputs. The most important changes are:
1. `.github/workflows/fuzzing.yml`: Permissions for the fuzzing workflow have been changed from read to write.
2. `.github/workflows/fuzzing.yml`: The trigger for the fuzzing workflow has been changed from a workflow call to a daily schedule at 21:00 UTC and a manual dispatch.
3. `.github/workflows/fuzzing.yml`: The use of inputs has been replaced with environment variables. This change affects the platform and architecture parameters used in the …
> Move fuzzing to it's own workflow

- .github/workflows/fuzzing.yml
This pull request includes changes to the `.github/workflows/fuzzing.yml` file, which is part of the GitHub Actions workflow. The changes primarily focus on replacing the use of environment variables with a matrix strategy for the job configurations. This allows for more flexibility in defining and managing the job configurations.
Here are the most important changes:
* Replaced the `env:` block with a `strategy:` block that uses a matrix to define `platform` and `arch` parameters. This change allows for more flexibility in defining and managing the job configurations.
* Updated the `runs-on:` field to use the `matrix.platform` value instead of the `env.platform` value. This change is in line with the switch to a matrix strategy.
* Updated the `run:` field in the "Generate the cache key" …
> Create matrix for fuzzing

- vm/ubpf_jit_x86_64.c
- vm/ubpf_jit_x86_64.h
- vm/ubpf_vm.c
All ALU32 operations are supposed to truncate the target register. Adding code to ensure that this is always done.
> Truncate all ALU32 except for bit-endianess

- .github/workflows/fuzzing.yml
This pull request includes changes to the `fuzzing.yml` workflow file in the `.github/workflows` directory. The changes primarily involve updating the versions of the GitHub Actions used in the workflow. The versions of `actions/checkout`, `actions/cache`, and `actions/upload-artifact` have been updated to specific commit hashes instead of version tags.
Here are the key changes:
- [`.github/workflows/fuzzing.yml`](diffhunk://#diff-0d1818478ed3978a08c330da0345293a51e13da847c4f41d494b346c3615b94cL26-R26): The `actions/checkout` action has been updated from version `v4.1.6` to commit hash `a5ac7e51b41094c92402da3b24376905380afc29`. This change occurs twice in the workflow, once at the beginning and once later in the workflow. [[1]](diffhunk://#diff-0d1818478ed3978a08c330da0345293a51e13da847c4 …
> Pin dependencies

- .github/workflows/main.yml
This pull request introduces changes to the GitHub Actions workflow configuration in the `.github/workflows/main.yml` file. The changes involve the addition of four new jobs for CodeQL analysis on different build types and configurations.
The key changes are:
* Addition of new CodeQL analysis jobs:
* [`linux_release_codeql`](diffhunk://#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e9203777f6b2e379d9e4882b3R314-R347): This job uses the `posix.yml` workflow to run a CodeQL analysis on a `RelWithDebInfo` build type on `ubuntu-latest` platform with `x86_64` architecture.
* [`linux_debug_codeql`](diffhunk://#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e9203777f6b2e379d9e4882b3R314-R347): Similar to the above job, but runs the CodeQL analysis on a `Debug` build type.
* …
> Enable codeql

- vm/ubpf_vm.c
On the inner most bpf2bpf call, the code attempts to capture the stack usage. This results in overwriting the bounds of the stack_frames array.
Resolves: #481
> Don't attempt to capture stack usage for inner most bpf2bpf call

- .github/workflows/fuzzing.yml
- .github/workflows/main.yml
- .github/workflows/posix.yml
This pull request includes changes to the GitHub Actions workflow file `.github/workflows/main.yml`. The changes involve updating the macOS platform version from `macos-11` to `macos-latest` for various jobs in the workflow. 
Here are the key changes:
* `.github/workflows/main.yml`: Updated the macOS platform version for the following jobs:
* [`macos_release`](diffhunk://#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e9203777f6b2e379d9e4882b3L69-R77): This job now uses the `macos-latest` platform instead of `macos-11`.
* [`macos_release_coverage`](diffhunk://#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e9203777f6b2e379d9e4882b3L86-R94): This job now uses the `macos-latest` platform instead of `macos-11`.
* [`macos_release_sanitizers`](diffhunk://#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e …
> Update to macos-latest

- libfuzzer/README.md
- libfuzzer/libfuzz_harness.cc
- libfuzzer/split.sh
- ubpf/disassembler.py
- vm/inc/ubpf.h
- vm/ubpf_int.h
- vm/ubpf_vm.c
This pull request includes changes to improve the `ubpf` library. The most important changes include adding a new libfuzzer based fuzzer, modifying the `LLVMFuzzerTestOneInput` function to compare the results of the interpreter and JIT compiler, adding a bash script to split the fuzzer input into a program and memory, and adding bounds checking for memory accesses.
Improvements to fuzzing:
* [`libfuzzer/README.md`](diffhunk://#diff-ec67aab0b02e9ef86ef2b779f818f9e937c48440fe4b11fab3eccfc025ca40e7R1-R94): Added instructions for building and running a new libfuzzer based fuzzer.
* [`libfuzzer/libfuzz_harness.cc`](diffhunk://#diff-90d0c71847f23efa012693fe27bf93e459ad6a1b101cb48db77dd6205fbaf524R92-R98): Modified the `LLVMFuzzerTestOneInput` function to compare the results of the interpreter …
> Reject BPF program if uninitialized stack or registers are accessed during interpret path

- vm/ubpf_vm.c
Ensure that the value being shifted is 8bytes before shifting to prevent potential issues when assigning the result to 8byte value.
> Shifting 4byte then casting to 8byte may result in unexpected behavior

- vm/compat/windows/endian.h
- vm/ubpf_jit_arm64.c
- vm/ubpf_jit_x86_64.c
This pull request primarily focuses on updating the subproject commit in `external/bpf_conformance` and adding new instructions to the `translate` function in both the `vm/ubpf_jit_arm64.c` and `vm/ubpf_jit_x86_64.c` files. The new instructions are designed to handle specific immediate values in the `EBPF_OP_LE` and `EBPF_OP_BE` cases.
Subproject update:
* [`external/bpf_conformance`](diffhunk://#diff-4c83d0aeb8e3e2e0d8a21794f8e46b59c88fa31939be349410b94f4979813a74L1-R1): Updated the subproject commit from `ce9571054cb6e60ed88bddcfc8cbff19dc31dab6` to `032f73030556d08e98669e1eb9d86cce3dddf464`.
Addition of new instructions:
* [`vm/ubpf_jit_arm64.c`](diffhunk://#diff-854aae9d8e9fac050d2acfa7745f604fa16e119484bdedd095fe441a0a7220f4R1070-R1073): In the `translate` function, added a new …
> Make le16 and le32 truncate on x64

- vm/ubpf_vm.c
Resolves: #411 
Mask the high bits when doing arithmetic shift operations to prevent undefined behavior.
> Mask the high bits when doing shift operations

- vm/ubpf_vm.c
The variable stack_frames is located on the stack and not dynamically allocated. Freeing it results in undefined behavior.
> Freeing stack memory via free is undefined behavior

- tests/call0.data
- vm/ubpf_int.h
- vm/ubpf_jit_arm64.c
- vm/ubpf_jit_support.c
- vm/ubpf_jit_support.h
- vm/ubpf_jit_x86_64.c
- vm/ubpf_jit_x86_64.h
The interpreter already supports functions that happen to be in more than one function. This patch adds that support to the JIT.
Fixes #437
> Update JIT to handle overlapping instructions

- custom_tests/CMakeLists.txt
- custom_tests/srcs/ubpf_custom_test_support.cc
- custom_tests/srcs/ubpf_custom_test_support.h
- custom_tests/srcs/ubpf_test_external_dispatcher_context_overwrite.cc
- custom_tests/srcs/ubpf_test_external_dispatcher_simple_context.cc
- custom_tests/srcs/ubpf_test_external_stack_contents.cc
- custom_tests/srcs/ubpf_test_frame_pointer.cc
- custom_tests/srcs/ubpf_test_jit_unexpected_instruction.cc
- custom_tests/srcs/ubpf_test_update_dispatcher.cc
- custom_tests/srcs/ubpf_test_update_helpers.cc
- custom_tests/windows/test.cmd
This pull request primarily refactors the way custom tests are set up and executed in the `custom_tests` directory. The changes include modifying the test command in `CMakeLists.txt`, adding a new function to get the program string from command line arguments or standard input, and updating various test files to use this new function.
Changes to test setup:
* [`custom_tests/CMakeLists.txt`](diffhunk://#diff-6f7adf7c9ecbf38bde4f574c7f10ba2bc6c11428160ed66fa010d9a73efb2982L60-R60): Modified the test command to directly execute the test executable with a `--program` argument pointing to the potential input file, instead of using a Windows command script to pipe the input file into the test executable.
* [`custom_tests/srcs/ubpf_custom_test_support.cc`](diffhunk://#diff-f4d6dcea913657efea96068 …
> Improve CLI handling by permitting either std::cin or file for program data

- tests/ldxb-0offset.data
- tests/ldxb-large-offset.data
- tests/ldxb-small-offset.data
- vm/ubpf_jit_x86_64.h
When register R12 is used in an instruction requiring a ModRM byte, the semantics and encoding of the instruction are unique. The emit_modrm_and_displacement function did not handle this uniqueness properly. This patch modifies the function to handle the use of R12 correctly.
Fixes #529
> Emit ModRM Correctly When Register R12 Is Used

- tests/err-call-bad-imm.data
- vm/ubpf_vm.c
As mentioned in #425 , we have dispatcher now, but it is still limited by MAX_EXT_FUNCS. Release this limit when we use dispatcher.
> allow calling helpers larger than MAX_EXT_FUNCS when using dispatcher

- .github/workflows/fuzzing.yml
This pull request includes a small change to the `.github/workflows/fuzzing.yml` file. The change updates the version of the `upload-artifact` action to the latest version.
* [`.github/workflows/fuzzing.yml`](diffhunk://#diff-0d1818478ed3978a08c330da0345293a51e13da847c4f41d494b346c3615b94cL150-R150): Updated `actions/upload-artifact` from `82c141cc518b40d92cc801eee768e7aafc9c2fa2` to `65462800fd760344b1a7b4382951275a0abb4808` (v4.3.3).
> Fix actions/upload-artifact version

- .github/workflows/posix.yml
- .github/workflows/windows.yml
This pull request introduces a new step to rerun failed tests with more verbose output in the CI workflows for both POSIX and Windows environments. This change aims to improve the debugging process by providing more detailed information when tests fail.
Improvements to CI workflows:
* [`.github/workflows/posix.yml`](diffhunk://#diff-258c8e6cdf61e87e9d94e06c76fb5e23f602423313565dcb8a46afe648587aceR194-R199): Added a step to rerun failed tests with more verbose output if the platform is `ubuntu-latest` and there is a failure. (`[.github/workflows/posix.ymlR194-R199](diffhunk://#diff-258c8e6cdf61e87e9d94e06c76fb5e23f602423313565dcb8a46afe648587aceR194-R199)`)
* [`.github/workflows/windows.yml`](diffhunk://#diff-5ce5c9ff86f58b1f87b35b5227b2e84cb69f022d6741e1854f3e1e181091773cR81-R86): Added a …
> Rerun tests with logging on failure

- .github/workflows/fuzzing.yml
- .github/workflows/main.yml
- .gitmodules
- CMakeLists.txt
- cmake/options.cmake
- custom_tests/srcs/ubpf_test_debug_function.cc
- libfuzzer/CMakeLists.txt
- libfuzzer/libfuzz_harness.cc
- libfuzzer/libfuzzer_config.h.inc
- vm/inc/ubpf.h
- vm/ubpf_vm.c
This pull request integrates the eBPF verifier as a submodule and updates the `libfuzzer` harness to utilize the verifier. The changes include modifications to submodule configurations, build scripts, and the addition of new verification and debugging functionalities in the `libfuzzer` harness.
* [`.gitmodules`](diffhunk://#diff-fe7afb5c9c916e521401d3fcfb4277d5071798c3baf83baf11d6071742823584R7-R9): Added the `ebpf-verifier` submodule.
* [`CMakeLists.txt`](diffhunk://#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR46): Included the `ebpf-verifier` directory in the build when `UBPF_ENABLE_LIBFUZZER` is enabled.
* [`external/ebpf-verifier`](diffhunk://#diff-0f47f98c433f156a9980e12abb7595d356ac1690a2e6ddbc3d51f7a4f0c7621eR1): Added the submodule commit reference for …
> Verifier integration

- .github/workflows/fuzzing.yml
- .github/workflows/main.yml
- .github/workflows/windows.yml
- CMakeLists.txt
- libfuzzer/CMakeLists.txt
- libfuzzer/libfuzz_harness.cc
This pull request introduces support for Windows in the fuzzing workflow and makes various related adjustments to the build configuration and scripts. The most important changes include adding Windows as a platform in the CI matrix, modifying the build configuration for compatibility with Windows, and updating artifact naming conventions.
* [`.github/workflows/fuzzing.yml`](diffhunk://#diff-0d1818478ed3978a08c330da0345293a51e13da847c4f41d494b346c3615b94cR21): Added Windows as a supported platform in the CI matrix and included platform-specific configuration steps for building and running the fuzzing jobs. [[1]](diffhunk://#diff-0d1818478ed3978a08c330da0345293a51e13da847c4f41d494b346c3615b94cR21) [[2]](diffhunk://#diff-0d1818478ed3978a08c330da0345293a51e13da847c4f41d494b346c3615b94cL89-R91) …
> Fix Windows build of ubpf_fuzzer

- CMakeLists.txt
- libfuzzer/libfuzz_harness.cc
- tests/err-call-invalid-jump.data
- tests/err-call0.data
- vm/ubpf_vm.c
This pull request includes several changes to improve the robustness and functionality of the eBPF verifier and the UBPF virtual machine. The most significant changes involve adding error handling to the fuzzer harness, updating the submodule for the eBPF verifier, and enhancing the UBPF VM to ensure the integrity of sub-programs.
* [`libfuzzer/libfuzz_harness.cc`](diffhunk://#diff-90d0c71847f23efa012693fe27bf93e459ad6a1b101cb48db77dd6205fbaf524L819-R817): Added try-catch block in `LLVMFuzzerTestOneInput` to catch and log exceptions, improving error handling during fuzz testing. [[1]](diffhunk://#diff-90d0c71847f23efa012693fe27bf93e459ad6a1b101cb48db77dd6205fbaf524L819-R817) [[2]](diffhunk://#diff-90d0c71847f23efa012693fe27bf93e459ad6a1b101cb48db77dd6205fbaf524R880-R883)
* …
> Only permit jumps within sub-programs

- .gitmodules
This pull request includes updates to the `.gitmodules` file and the `external/ebpf-verifier` submodule to point to a different repository and commit, respectively.
Submodule updates:
* [`.gitmodules`](diffhunk://#diff-fe7afb5c9c916e521401d3fcfb4277d5071798c3baf83baf11d6071742823584L9-R9): Changed the URL for the `external/ebpf-verifier` submodule to `https://github.com/alan-jowett/ebpf-verifier.git` from the previous URL.
* [`external/ebpf-verifier`](diffhunk://#diff-0f47f98c433f156a9980e12abb7595d356ac1690a2e6ddbc3d51f7a4f0c7621eL1-R1): Updated the submodule commit to `71a500ce9bbe33cb48eff075f0f859b8cb62df74` from the previous commit.
> Switch to fuzzing branch

- vm/ubpf_vm.c
Loading an uninitialized value from the stack should mark the destination register as uninitialized.
> Mark register as uninitialized if source is uninitialized stack

- .github/workflows/fuzzing.yml
- ubpf/dictionary_generator.py
This pull request includes updates to the fuzzing workflow and the addition of a new script for generating a dictionary of BPF instructions. The most important changes include modifications to the `.github/workflows/fuzzing.yml` file and the addition of the `ubpf/dictionary_generator.py` script.
* [`.github/workflows/fuzzing.yml`](diffhunk://#diff-0d1818478ed3978a08c330da0345293a51e13da847c4f41d494b346c3615b94cR110-R118): Added steps to generate a dictionary of BPF instructions for both Linux and Windows platforms. [[1]](diffhunk://#diff-0d1818478ed3978a08c330da0345293a51e13da847c4f41d494b346c3615b94cR110-R118) [[2]](diffhunk://#diff-0d1818478ed3978a08c330da0345293a51e13da847c4f41d494b346c3615b94cR156-R159)
* [`.github/workflows/fuzzing.yml`](diffhunk://#diff-0d1818478ed3978a08c330da034529 …
> Generate dictionary

- .github/workflows/fuzzing.yml
- libfuzzer/libfuzz_harness.cc
This pull request includes updates to the fuzzing workflow and an update to the `ebpf-verifier` submodule. The most important changes are as follows:
* [`.github/workflows/fuzzing.yml`](diffhunk://#diff-0d1818478ed3978a08c330da0345293a51e13da847c4f41d494b346c3615b94cL227-R227): Added an environment variable `UBPF_FUZZER_CONSTRAINT_CHECK` to the fuzzing command to enable constraint checking during fuzzing.
* [`external/ebpf-verifier`](diffhunk://#diff-0f47f98c433f156a9980e12abb7595d356ac1690a2e6ddbc3d51f7a4f0c7621eL1-R1): Updated the submodule to a new commit to include the latest changes from the `ebpf-verifier` repository.
> Enable constraints check on Linux

- .github/workflows/fuzzing.yml
This pull request includes a small but important change to the `.github/workflows/fuzzing.yml` file. The change ensures that the latest updates are pulled from the repository before merging the corpus during scheduled events.
* [`.github/workflows/fuzzing.yml`](diffhunk://#diff-0d1818478ed3978a08c330da0345293a51e13da847c4f41d494b346c3615b94cR238): Added a `git pull` command to ensure the latest updates are included before running the corpus merge.
> Pull after running fuzzing to avoid conflict

- .github/workflows/fuzzing.yml
- .github/workflows/main.yml
This pull request includes updates to the fuzzing workflow configuration to improve runtime flexibility based on the event type. The key changes involve setting a default runtime for fuzzing and adjusting it for scheduled jobs.
* [`.github/workflows/fuzzing.yml`](diffhunk://#diff-0d1818478ed3978a08c330da0345293a51e13da847c4f41d494b346c3615b94cR212-R226): Added a default runtime of 5 minutes for the fuzzer and increased the runtime to 2 hours for scheduled or manually triggered jobs.
* [`.github/workflows/fuzzing.yml`](diffhunk://#diff-0d1818478ed3978a08c330da0345293a51e13da847c4f41d494b346c3615b94cL227-R248): Updated the fuzzer execution command to use the runtime specified in the environment variable `UBPF_FUZZER_RUNTIME`.
> Increase runtime

- vm/ubpf_instruction_valid.c
This pull request includes changes to the `vm/ubpf_instruction_valid.c` file to improve type safety and consistency in the `_initialize_lookup_table` and `_in_range` functions.
Improvements to type safety and consistency:
* [`vm/ubpf_instruction_valid.c`](diffhunk://#diff-9f21b38f4b43f04732f43980ba8a33b4a4c6e528129cb9d40d0e5a044b0348faL957-R965): Changed the loop variable type from `int` to `size_t` in the `_initialize_lookup_table` function to ensure proper handling of the loop index.
* [`vm/ubpf_instruction_valid.c`](diffhunk://#diff-9f21b38f4b43f04732f43980ba8a33b4a4c6e528129cb9d40d0e5a044b0348faL957-R965): Updated the parameter types in the `_in_range` function from `int` to `int32_t` for better consistency and clarity.
> Fix integer widths

- .github/workflows/fuzzing.yml
This pull request includes changes to the fuzzing job configurations in the `.github/workflows/fuzzing.yml` file to adjust the maximum total run time for the fuzzing process.
Changes to fuzzing job configurations:
* Reduced the `max_total_time` for the `ubpf_fuzzer` from 7200 seconds to 3600 seconds for both the `ubuntu-24.04` and `windows-latest` platforms.
> Set timeout correctly

- libfuzzer/CMakeLists.txt
- libfuzzer/libfuzz_harness.cc
This pull request includes several updates to the `libfuzzer` harness to enhance the functionality and remove outdated checks. The most important changes involve adding new fields to the `ubpf_context_t` structure, removing conditional compilation checks, and updating function signatures to include the program code.
* Added `program_start` and `program_end` fields to the `ubpf_context_t` structure to track the program boundaries. (`libfuzzer/libfuzz_harness.cc`)
* Removed the `HAVE_EBPF_VERIFIER_CHECK_CONSTRAINTS_AT_LABEL` conditional compilation checks and related code, simplifying the handling of `store_pre_invariants` option. (`libfuzzer/libfuzz_harness.cc`) [[1]](diffhunk://#diff-90d0c71847f23efa012693fe27bf93e459ad6a1b101cb48db77dd6205fbaf524L362-L364) …
> Fix labelling for local calls

- .github/workflows/fuzzing.yml
This pull request includes a minor update to the fuzzing workflow configuration in the `.github/workflows/fuzzing.yml` file. The change introduces a timeout parameter to the `ubpf_fuzzer` command to prevent it from running indefinitely.
* Added a `-timeout=60` parameter to the `ubpf_fuzzer` command for both Ubuntu and Windows platforms to ensure the fuzzer does not run indefinitely. (`.github/workflows/fuzzing.yml`)
> Set timeout on fuzzing

- vm/inc/ubpf.h
This pull request includes changes to the `vm/inc/ubpf.h` file to update the configuration of the uBPF VM. The most important changes involve setting a default maximum number of nested calls and adjusting the default stack size accordingly.
Configuration updates:
* Added a new definition for `UBPF_MAX_CALL_DEPTH` with a default value of 8 if not already defined.
* Adjusted the default stack size (`UBPF_EBPF_STACK_SIZE`) to be calculated based on `UBPF_MAX_CALL_DEPTH`.
* Removed an older definition for `UBPF_MAX_CALL_DEPTH` that set the value to 10.
> Set stack as function of max call depth

- vm/ubpf_jit_arm64.c
- vm/ubpf_jit_support.c
- vm/ubpf_jit_support.h
- vm/ubpf_jit_x86_64.c
Until now, special targets during JITing were handled using constant valudes that _could_ be valid addresses on certain architectures. To disambiguate, this patch adds more precise metadata for each target.
> Cleanup Handling of Targets During JITing.

- .github/workflows/posix.yml
Resolves: #630
This pull request includes a minor change to the `.github/workflows/posix.yml` file. The change modifies the `lcov` command to ignore all errors during the code coverage capture process.
* [`.github/workflows/posix.yml`](diffhunk://#diff-258c8e6cdf61e87e9d94e06c76fb5e23f602423313565dcb8a46afe648587aceL204-R204): Updated the `lcov` command to use the `--ignore-errors all` flag instead of `--ignore-errors inconsistent` to ensure all errors are ignored during the code coverage capture.
> Handle changes to lcov

- scripts/format-code
Hey, great project you got going on!
My recent version of clang-format (v19) seems inconsistent with the formatting 
both in this repo and the submodules. So after running `scripts/format-code`, git
told me I had modified files within one of these - namely `vm/compat/libraries/win-c/src`.
I'm still trying to get the correct version of clang setup, but in the meantime I thought
it wouldn't hurt to prune git submodules for the format check. 
I couldn't find a way to prune them through `find`, so I figured I'd use `grep`.
Let me know if this is intentional or if you'd like to see a different solution. 
Thanks!
ps.
These are the files I believe are needlessly getting format checked:
```
./vm/compat/libraries/win-c/src/test/test_getopt_long.cpp
./vm/compat/libraries/win-c/src/test/test.cpp …
```
> Prune git submodules in format script

- vm/ubpf_loader.c
Apologies for the VERY small PR, but this prevents loading some ELF files because of the relocation loading process and may block others with similar binaries and might be useful.
As described in Issue 510, I believe that the condition ">" should be ">=" when searching for relocated functions because it is possible (and has happened) that the offset of the relocation is equal to the offset of the function (i.e. the relocation happened at the very first byte of the function).
I therefore believe that the ">" should be changed to ">=" in this loop checking whether the offset is "inside" a particular function.
> Issue 510: Wrong conditional for offset check in ELF relocation

- CMakeLists.txt
As far as I can tell, this was the originally intended purpose of the `UBPF_SKIP_EXTERNAL` flag.
Usecase: I need a way to build without pulling down the (enormous) submodules.
> Fix UBPF_SKIP_EXTERNAL CMake option

- .github/workflows/posix.yml
This pull request makes a minor update to the macOS build workflow configuration. The change removes the installation of `cmake` from the list of packages installed via Homebrew.
* [`.github/workflows/posix.yml`](diffhunk://#diff-258c8e6cdf61e87e9d94e06c76fb5e23f602423313565dcb8a46afe648587aceL129): Removed `cmake` from the list of packages installed by Homebrew for the macOS build job.
> MacOS build fails to install cmake
